// <auto-generated />
namespace App.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_ticket_seatnumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ticket_seatnumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100539452_add_ticket_seatnumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
